pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-21'
                    reuseNode true
                }
            }
            steps {
                sh '''
                ls -la
                cd test_deepseek
                ls -la
                java -version
                mvn -version
                mvn clean package -DskipTests
                ls -la target/
                '''
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-21'
                    reuseNode true
                }
            }
            steps {
                sh '''
                cd test_deepseek
                mvn test jacoco:report
                '''
            }
            post {
                always {
                    junit 'test_deepseek/target/surefire-reports/*.xml'
                    jacoco execPattern: '**/target/jacoco.exec'
                }
            }
        }

        stage('SonarQube Analysis') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-21'
                    reuseNode true
                }
            }
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                    cd test_deepseek
                    mvn sonar:sonar \
                        -Dsonar.projectKey=spring-boot-deep-seek \
                        -Dsonar.host.url=http://192.168.110.186:9000 \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    script {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline failed due to SonarQube quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }
    }
}
